#Server:
#  AppVersion: "1.0.0"
#  Host: "0.0.0.0"
#  Port: "11037"
#  Timeout: 60s


Postgres:
  host: "0.0.0.0"
  port: "5555"
  user: "postgres"
  password: "postgres"
  DBName: "postgres"
  sslMode: "require"
  pgDriver: "pgx"


Telegram:
  token: "your token"

logger:
  level: "debug"
  inFile: "./logs/app.log"
  development: false
  disableCaller: false
  disableStacktrace: true
  encoding: "json"